stages:
  - build

before_script:
  - docker login -u gitlab-ci-token -p ${CI_JOB_TOKEN} ${CI_REGISTRY}

build:
  stage: build
  script:
    - docker build --build-arg NEXUS_VERSION=${CI_COMMIT_TAG%%-*} --build-arg NEXUS_VERSION_BUILD=${CI_COMMIT_TAG##*-} -t ${CI_REGISTRY}/images/oss-nexus:${CI_COMMIT_TAG%%-*} . -f Dockerfile
    - docker push ${CI_REGISTRY}/images/oss-nexus:${CI_COMMIT_TAG%%-*}
  except:
    - schedules
  only:
    - tags
  tags:
    - build

